version: 2
jobs:
   build:
     docker:
       - image: circleci/node:latest
     steps:
       - checkout
       - run: npm install
       - run: npm install --prefix ./client
       - run: npm install --prefix ./server
       - run: npm run build --prefix ./client
       - run: git log --oneline --decorate > client/public/changelog.txt
       - run: cp server/package.json sever/app/
       - run: node deploy_server.js
       - run: node deploy_app.js

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
               - master