version: 2
jobs:
   build:
     docker:
       - image: circleci/node:latest
     steps:
       - checkout
       - add_ssh_keys:
          fingerprints:
            - "96:ee:27:45:1b:05:d4:fe:a6:95:a8:4b:a9:f9:55:32"
       - run: npm install
       - run: npm install --prefix ./client
       - run: npm install --prefix ./server
       - run: npm run build --prefix ./client
       - run: npm run build --prefix ./server
       - run: git log --oneline --decorate > client/public/changelog.txt
       - run: cp server/package.json server/build/
       - run: node deploy_server.js
       - run: node deploy_app.js
       - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "ls"


workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
               - master