version: 2
jobs:
   build:
     docker:
       - image: circleci/node:latest
     steps:
       - checkout
       - add_ssh_keys:
          fingerprints:
            - "63:35:65:9c:29:05:3f:fd:de:b4:b5:44:08:61:ce:39"
       - run: npm install
       - run: npm install --prefix ./client
       - run: npm install --prefix ./server
       - run: npm run build --prefix ./client
       - run: npm run build --prefix ./server
       - run: git log --oneline --decorate > client/public/changelog.txt
       - run: cp server/package.json server/build/
       - run: node deploy_server.js
       - run: node deploy_app.js
workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
               - master